"use client";
import { Award, Check, Lock, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { achievementLevel, achievementLevels, type Achievement, type AchievementLedger } from "@/lib/achievements";
export default function AchievementGallery({badges,ledger}:{badges:Achievement[];ledger:AchievementLedger}) {
  const earned=useMemo(()=>new Set(Object.keys(ledger)),[ledger]),level=achievementLevel(earned.size),[selected,setSelected]=useState<number|null>(null);
  const visibleLayer=selected!==null&&selected<=level?selected:level,next=achievementLevels[level+1],material=achievementLevels[level];
  const grouped=badges.filter(badge=>badge.layer===visibleLayer);
  return <><div className="achievement-banner material-banner" style={{background:material.background,color:material.ink}}><span style={{background:material.colour,color:material.onColour}}><Award size={44}/></span><div><p className="section-label">COMMON EARTH TO RARE TREASURES</p><h2>{material.name} · {earned.size} permanent achievements</h2><p>{material.description} {next?`${next.name} opens at ${next.threshold} earned achievements.`:"Every layer is open. Keep noticing new things."}</p><p className="small">{badges.length} possibilities. Calendar-day badges can be earned before their layer opens and remain forever.</p></div></div>
    <div className="material-scale" aria-label="Achievement materials from common to rare">{achievementLevels.map((item,index)=><button key={item.name} onClick={()=>setSelected(index)} disabled={index>level} aria-pressed={visibleLayer===index} style={{background:visibleLayer===index?item.colour:item.background,color:visibleLayer===index?item.onColour:item.ink,borderColor:item.colour}}><span>{index>level?<Lock size={15}/>:<Sparkles size={15}/>} {index+1}. {item.name}</span><small>{index>level?`Opens at ${item.threshold}`:`${badges.filter(badge=>badge.layer===index&&earned.has(badge.id)).length} / ${badges.filter(badge=>badge.layer===index).length} earned`}</small></button>)}</div>
    <p className="small muted material-intro">{achievementLevels[visibleLayer].description} Archiving or deleting a photo does not remove an earned badge.</p>
    <div className="achievement-grid">{grouped.map(badge=>{const unlocked=earned.has(badge.id),colour=achievementLevels[badge.layer],progress=unlocked?badge.goal:badge.progress;return <article key={badge.id} className={"achievement material-achievement "+(unlocked?"unlocked":"")} style={{borderColor:colour.colour,background:unlocked?colour.background:"#fffdf7"}}><div className="badge-icon" style={{background:colour.background,color:colour.ink}}><Award size={35}/>{unlocked&&<span style={{background:colour.colour,color:colour.onColour}}><Check size={12}/></span>}</div><span className="badge-state" style={{color:colour.ink}}>{colour.name.toUpperCase()} · {unlocked?"EARNED FOREVER":"STILL TO DISCOVER"}</span><h2>{badge.name}</h2><p>{badge.description}</p><div className="progress-track" role="progressbar" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={badge.goal} aria-label={badge.name}><i style={{width:`${progress/badge.goal*100}%`,background:colour.colour}}/></div><small>{unlocked?`Earned ${new Date(ledger[badge.id]).toLocaleDateString('en-GB')}`:`${progress} of ${badge.goal}`}</small></article>;})}</div>
  </>;
}
