"use client";
import { Camera, Sparkles } from "lucide-react";
import { useEffect, useRef, useState, type FormEvent } from "react";
type AvatarStatus = {avatar:{kind?:string;imageUrl?:string};generationEnabled:boolean;remainingGenerations:number;generationLimit:number;period:string;allowanceDescription:string};
function safeAvatar(value?:string) {return typeof value==="string"&&/^\/api\/avatar\/image\?revision=[a-f0-9-]{36}$/i.test(value)?value:"";}
export default function AvatarMaker({onChanged}:{onChanged:()=>void}) {
  const [status,setStatus]=useState<AvatarStatus|null>(null), [portrait,setPortrait]=useState<Blob|null>(null), [preview,setPreview]=useState(""), [error,setError]=useState(""), [busy,setBusy]=useState(false), [success,setSuccess]=useState(false);
  const input=useRef<HTMLInputElement>(null), attempt=useRef<string|null>(null);
  async function refresh() {const response=await fetch("/api/avatar",{cache:"no-store"});const data=await response.json() as AvatarStatus & {error?:string};if(!response.ok)throw Error(data.error||"Sign in to make an avatar.");setStatus(data);}
  useEffect(()=>{void refresh().catch(cause=>setError(cause.message));},[]);
  useEffect(()=>{if(!portrait){setPreview("");return;}const url=URL.createObjectURL(portrait);setPreview(url);return()=>URL.revokeObjectURL(url);},[portrait]);
  async function choose(file?:File) {
    if(!file)return;setBusy(true);setError("");setSuccess(false);setPortrait(null);attempt.current=null;
    try {if(file.size>20*1024*1024||!/^image\/(jpeg|png|webp)$/.test(file.type))throw Error("Choose a JPEG, PNG or WebP portrait smaller than 20 MB.");const image=await createImageBitmap(file);try{const scale=Math.min(1,1024/Math.max(image.width,image.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const context=canvas.getContext("2d");if(!context)throw Error("This browser cannot prepare the photo.");context.fillStyle="#fff";context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0,canvas.width,canvas.height);const photo=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(Error("Could not prepare the portrait.")),"image/jpeg",.85));if(photo.size>2*1024*1024)throw Error("Please choose a simpler or smaller portrait.");setPortrait(photo);}finally{image.close();}}
    catch(cause){setError(cause instanceof Error?cause.message:"That portrait could not be opened.");}finally{setBusy(false);if(input.current)input.current.value="";}
  }
  async function generate(event:FormEvent<HTMLFormElement>) {
    event.preventDefault();if(!portrait||busy)return;setBusy(true);setError("");if(!attempt.current)attempt.current=crypto.randomUUID();
    const form=new FormData();form.set("photo",portrait,"portrait.jpg");form.set("consent","true");form.set("requestId",attempt.current);
    try{const response=await fetch("/api/avatar/photo",{method:"POST",body:form});const data=await response.json() as AvatarStatus & {error?:string};if(!response.ok)throw Error(data.error||"The avatar could not finish. Your previous avatar is unchanged.");if(!safeAvatar(data.avatar?.imageUrl))throw Error("The generated avatar was not available. Refresh your profile.");setStatus(current=>current?{...current,avatar:data.avatar,remainingGenerations:data.remainingGenerations}:null);setPortrait(null);attempt.current=null;setSuccess(true);onChanged();void refresh().catch(()=>{});}
    catch(cause){setError(cause instanceof Error?cause.message:"The connection was interrupted. Retry uses the same request reference.");void refresh().catch(()=>{});}finally{setBusy(false);}
  }
  return <form className="form-stack avatar-maker" onSubmit={generate}><p className="muted">A warm cartoon portrait, made from your photo in My Trail Log’s illustrated style. Only the cartoon is used on your profile.</p>{status&&safeAvatar(status.avatar?.imageUrl)&&<img src={safeAvatar(status.avatar.imageUrl)} className="avatar-maker-current" alt="Your current illustrated avatar"/>}{status&&<p className="small muted">{status.allowanceDescription||`${status.remainingGenerations} generation available`}. A processing attempt uses an allowance even if it cannot finish.</p>}{status&&!status.generationEnabled&&<p className="notice">Avatar generation is not available yet. Your current avatar remains unchanged.</p>}{error&&<p className="notice error" role="alert">{error}</p>}{success&&<p className="notice" role="status">Your illustrated avatar is ready. Your original portrait was not saved to My Trail Log.</p>}<input type="file" accept="image/jpeg,image/png,image/webp" capture="user" ref={input} onChange={event=>void choose(event.target.files?.[0])} className="visually-hidden" aria-label="Choose a portrait for your avatar"/><button type="button" className="button secondary full" disabled={busy||!status?.generationEnabled||status.remainingGenerations<=0} onClick={()=>input.current?.click()}><Camera size={20}/>{portrait?"Choose a different portrait":"Take or choose my photo"}</button>{preview&&<><img src={preview} className="avatar-maker-preview" alt="Your private source portrait, shown locally before sending"/><label className="checkbox"><input type="checkbox" name="consent" required disabled={busy}/>I have permission to use this photo and send it to OpenAI to create a cartoon avatar. My source photo is not stored in My Trail Log or shared with members. A processing attempt uses one allowance even if it cannot finish.</label><button className="button primary full" disabled={busy}><Sparkles size={20}/>{busy?"Making your avatar…":"Make my avatar"}</button></>}<p className="small muted">Your photo is sent only when you press Make my avatar. OpenAI’s processing and retention terms apply. <a href="/privacy">Privacy details</a>.</p></form>;
}
