"use client";
import { useEffect, useState } from "react";
type Billing = { plan: string; planName: string; limit: number; used: number; remaining: number; bonusRemaining: number; periodEnd: string; expiresAt: string | null; isTrial: boolean; trialRemaining: number | null; billingReady: boolean; verificationDelayed: boolean; annualBonusPending?: boolean; closerLookLimit: number; closerLooksUsed?: number; closerLooksRemaining?: number; annualBonusCloserLooksRemaining?: number; trialCloserLooksRemaining?: number | null; closerLookStatus?: "ready" | "used" | "temporarily-unavailable" | "verification-pending" };
export default function MembershipPanel() {
  const [billing, setBilling] = useState<Billing | null>(null), [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); fetch("/api/billing", { cache: "no-store", signal: controller.signal }).then(async response => { const data = await response.json() as Billing & { error?: string }; if (!response.ok) throw Error(data.error || "Sign in online to view your membership."); setBilling(data); }).catch(cause => { if (!controller.signal.aborted) setError(cause instanceof Error ? cause.message : "Connect to view your membership."); }); return () => controller.abort(); }, []);
  return <div className="form-stack"><p className="muted">Your account’s verified plan applies to the Android app and desktop journal.</p>{error && <p className="notice error" role="alert">{error}</p>}{!billing && !error && <p role="status">Checking your plan…</p>}{billing && <>
    <h3>{billing.planName || billing.plan}{billing.isTrial ? " · Free trial" : ""}</h3>
    <div className="notice"><div><strong>{billing.used.toLocaleString("en-GB")} cloud photos used this UTC month</strong><p>Monthly photo allowance: {billing.limit.toLocaleString("en-GB")}. Available uploads: {billing.remaining.toLocaleString("en-GB")}.{billing.bonusRemaining > 0 && ` This includes ${billing.bonusRemaining} annual bonus photos.`}</p>{billing.isTrial && <p>{billing.trialRemaining} uploads remain in this trial’s {billing.limit.toLocaleString("en-GB")}-photo total.</p>}</div></div>
    <div className="notice"><div><strong>Automatic closer reviews</strong>{Number.isFinite(billing.closerLooksUsed) && Number.isFinite(billing.closerLooksRemaining) ? <><p>{billing.closerLooksUsed!.toLocaleString("en-GB")} attempts used this UTC month. Normal allowance: {billing.closerLookLimit.toLocaleString("en-GB")}. Available closer reviews: {billing.closerLooksRemaining!.toLocaleString("en-GB")}.</p>{!!billing.annualBonusCloserLooksRemaining && <p>{billing.annualBonusCloserLooksRemaining} annual extra closer reviews remain, usable only for annual bonus photos.</p>}{billing.isTrial && Number.isFinite(billing.trialCloserLooksRemaining) && <p>{billing.trialCloserLooksRemaining} closer reviews remain in this trial’s {billing.closerLookLimit}-review total.</p>}</> : <p>Closer-review usage is temporarily unavailable. Reconnect to check your remaining allowance.</p>}<p>Smart AI may use a closer review automatically for an uncertain photo. Reserved or failed attempts use one allowance. Initial suggestions continue after the closer-review limit and may remain tentative.</p></div></div>
    {billing.closerLookStatus === "temporarily-unavailable" && <p className="notice">Closer reviews are temporarily unavailable. Your photos stay saved; initial suggestions continue.</p>}{billing.closerLookStatus === "verification-pending" && <p className="notice">Your closer-review allowance is awaiting membership verification. Restore purchases in the Android app.</p>}
    <p className="small muted">Next monthly reset: {new Date(billing.periodEnd).toLocaleDateString("en-GB")}.{billing.expiresAt && ` Current access ends ${new Date(billing.expiresAt).toLocaleDateString("en-GB")}.`}{billing.isTrial && " Calendar resets do not renew trial allowances. Annual extras are not included in a trial."}</p>
    {billing.annualBonusPending && <p className="notice">Annual extras are awaiting Google Play confirmation. Your monthly allowances are available.</p>}{billing.verificationDelayed && <p className="notice">Purchase verification is delayed. Restore purchases in the Android app; the server grants paid limits only after verification.</p>}
    <p className="small muted">{billing.billingReady ? "To subscribe or restore a purchase, open Membership in the Android app. Google Play shows your actual price and eligible trial terms." : "Paid subscriptions are being prepared. No payment or paid upgrade is available yet."}</p>
  </>}<a className="button secondary full" href="/pricing">Compare plans & allowances</a><a className="button secondary full" href="https://play.google.com/store/account/subscriptions" target="_blank" rel="noopener noreferrer">Manage Google Play subscriptions</a><p className="small muted">Your existing photos remain available and downloads always stay free. Deleting an account does not cancel a Google Play subscription.</p></div>;
}
