"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {LockKeyhole,ShieldCheck} from 'lucide-react';
type Status={configured:boolean;enabled:boolean;launchReady:boolean;pricingFinalised:boolean;secureStorageReady:boolean;serviceAccountEmail:string|null;packageName:string;missingChecks:string[]};
export default function PlaySetup() {
  const [status,setStatus]=useState<Status|null>(null),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[enabled,setEnabled]=useState(false),[launchReady,setLaunchReady]=useState(false),[securePage,setSecurePage]=useState(false);
  const formRef=useRef<HTMLFormElement>(null);
  function apply(value:Status){setStatus(value);setEnabled(value.enabled);setLaunchReady(value.launchReady);}
  useEffect(()=>{
    let alive=true;const controller=new AbortController();
    setSecurePage(window.location.protocol==='https:'||['localhost','127.0.0.1','[::1]'].includes(window.location.hostname));
    fetch('/api/admin/billing-setup',{credentials:'same-origin',cache:'no-store',signal:controller.signal}).then(async response=>{if(!alive)return;if(response.status===401||response.status===403)return;if(!response.ok)throw new Error('Secure payment setup is temporarily unavailable.');const value=await response.json() as Status;if(alive){apply(value);setVisible(true);}}).catch(cause=>{if(alive&&!(cause instanceof DOMException&&cause.name==='AbortError')){setError(cause instanceof Error?cause.message:'Payment setup is temporarily unavailable.');setVisible(true);}});
    const clear=()=>formRef.current?.reset();window.addEventListener('pagehide',clear);
    return()=>{alive=false;controller.abort();clear();window.removeEventListener('pagehide',clear);};
  },[]);
  async function save(event:FormEvent<HTMLFormElement>) {
    event.preventDefault();if(!securePage||busy)return;const form=event.currentTarget,values=new FormData(form),submitter=(event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement|null,action=submitter?.value==='disconnect'?'disconnect':'save';
    const payload:{password:string;serviceAccount?:string;enabled?:boolean;launchReady?:boolean;action:string;confirmDisconnect?:true}={password:String(values.get('password')||''),action};
    if(action==='disconnect'){if(!window.confirm('Disconnect Google verification and disable checkout? Existing Play subscriptions are not cancelled.'))return;payload.confirmDisconnect=true;}
    else{const account=String(values.get('serviceAccount')||'').trim();if(account)payload.serviceAccount=account;payload.enabled=enabled;payload.launchReady=launchReady;}
    form.reset();setBusy(true);setError('');setMessage('');
    try{
      const response=await fetch('/api/admin/billing-setup',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
      payload.password='';payload.serviceAccount='';const value=await response.json() as Status&{error?:string;message?:string};
      if(!response.ok){if(response.status===403)setVisible(false);throw new Error(value.error||'Payment setup could not be saved.');}
      apply(value);setMessage(value.message||'Payment setup saved securely.');
    }catch(cause){setError(cause instanceof Error?cause.message:'Check your connection and try again.');}
    finally{payload.password='';payload.serviceAccount='';form.reset();setBusy(false);}
  }
  if(!visible)return null;
  return <section className="company-admin-member" aria-labelledby="play-setup-title"><p className="company-kicker"><LockKeyhole size={16}/>Protected owner account only</p><h2 id="play-setup-title">Connect Google Play payments</h2><p>Enter the Google-issued credential directly on this private HTTPS page. It is encrypted on the server and never returned. Keep it out of chat, email and the app bundle.</p>
    {error&&<p role="alert" className="company-notice company-notice-error">{error}</p>}{message&&<p role="status" className="company-notice">{message}</p>}
    {status&&<><dl><div><dt>Credential</dt><dd>{status.configured?'Saved securely':'Not connected'}</dd></div><div><dt>Google service account</dt><dd>{status.serviceAccountEmail||'Not configured'}</dd></div><div><dt>Verification</dt><dd>{status.enabled?'Enabled':'Disabled'}</dd></div><div><dt>Checkout</dt><dd>{status.launchReady?'Ready flag enabled':'Disabled'}</dd></div></dl>{status.missingChecks.length>0&&<div className="company-notice"><h3>Before accepting a payment</h3><ul>{status.missingChecks.map(check=><li key={check}>{check}</li>)}</ul></div>}</>}
    <details><summary>Google setup steps</summary><ol><li>In Google Cloud, enable the Google Play Android Developer API and create a dedicated service account.</li><li>In Play Console → Users and permissions, grant that account access to <code>com.field.logger</code>, with View financial data/orders and Manage orders/subscriptions. Do not grant release/signing/user-management access.</li><li>Create the three subscription IDs: <code>trail_plus_monthly</code>, <code>trail_premium_monthly</code>, <code>trail_premium_yearly</code>. Configure monthly/yearly base plans and an eligible one-month introductory offer only after prices are finalised.</li><li>Download the Google service-account JSON privately, paste it below and save. The source JSON/password fields clear after each submitted attempt. Downloading a JSON key creates a long-lived credential; keep its backup private and rotate/revoke it in Google Cloud when needed.</li><li>Enable verification, upload the signed app to the existing Play test track, and test real license-tester purchases, restore, acknowledgement, expiry, cancellation and cross-account rejection.</li><li>Enable checkout only after actual prices/allowances, trader details and lifecycle tests match the app, website and Google products. A saved credential or this readiness flag does not prove a live purchase test passed.</li></ol><p><a href="https://developers.google.com/android-publisher/getting_started" target="_blank" rel="noreferrer">Google verification setup</a> · <a href="/pricing">Published plan availability</a> · <a href="/terms">Subscription terms</a></p></details>
    {!securePage?<p role="alert" className="company-notice company-notice-error">Open the HTTPS website before entering a credential.</p>:<form ref={formRef} onSubmit={save} className="company-admin-form" autoComplete="off"><label>Service-account JSON<textarea name="serviceAccount" rows={6} maxLength={30720} autoComplete="off" autoCorrect="off" autoCapitalize="none" spellCheck={false} onChange={event=>{if(event.target.value.trim())setLaunchReady(false);}} placeholder={status?.configured?'Leave blank to keep the saved credential':'Paste the Google-issued JSON here'} disabled={busy||!status?.secureStorageReady}/></label><p className="company-muted">Only the saved service-account email is shown afterwards. The private key stays encrypted. Leave this field blank to preserve the existing credential.</p><label style={{display:'flex',alignItems:'center',gap:10}}><input type="checkbox" checked={enabled} onChange={event=>{setEnabled(event.target.checked);if(!event.target.checked)setLaunchReady(false);}} disabled={busy||!status?.secureStorageReady}/>Enable server purchase verification</label><label style={{display:'flex',alignItems:'center',gap:10}}><input type="checkbox" checked={launchReady} onChange={event=>setLaunchReady(event.target.checked)} disabled={busy||!status?.configured||!enabled||!status?.pricingFinalised}/>I completed live Play tests and finalised the published plans; enable checkout</label><label>Confirm your owner password<input name="password" type="password" autoComplete="current-password" required minLength={8} maxLength={256} disabled={busy||!status?.secureStorageReady}/></label><div className="company-actions"><button className="company-button company-button-primary" name="action" value="save" disabled={busy||!status?.secureStorageReady}><ShieldCheck size={17}/>{busy?'Saving…':'Save securely'}</button>{status?.configured&&<button className="company-button company-button-danger" name="action" value="disconnect" disabled={busy}>Disconnect verification</button>}</div><p className="company-muted">Payment settings are restricted to the protected owner, require a password check and are audited. Disconnecting or deleting My Trail Log never cancels a member's Google Play subscription.</p></form>}
  </section>;
}
