"""End-to-end local acceptance checks. Uses a throwaway account and test photo."""
from playwright.sync_api import sync_playwright, expect
import uuid, json, os
BASE=os.environ.get('TEST_ORIGIN','http://localhost:8787')
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
    ctx=browser.new_context(viewport={'width':390,'height':844},device_scale_factor=1,is_mobile=True,has_touch=True,permissions=['geolocation'],geolocation={'latitude':51.752,'longitude':-1.258,'accuracy':7},accept_downloads=True)
    page=ctx.new_page(); errors=[]; page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto(BASE,wait_until='networkidle')
    expect(page.get_by_role('heading',name='Your field journal')).to_be_visible()
    page.evaluate('navigator.serviceWorker.ready')
    page.wait_for_function('navigator.serviceWorker.controller !== null')
    assert not page.evaluate('document.documentElement.scrollWidth > innerWidth')
    ctx.set_offline(True)
    page.locator('input[type=file]').nth(1).set_input_files('public/woodland.jpg')
    expect(page.get_by_role('heading',name='A new discovery')).to_be_visible()
    page.get_by_label('A name, if you know it').fill('QA bluebell woodland')
    page.get_by_label('Kind',exact=True).select_option('flowers')
    page.get_by_label('Place',exact=True).fill('QA Oxford woods')
    page.get_by_label('A little field note').fill('Testing an offline field note.')
    page.get_by_role('button',name='Use GPS',exact=True).click()
    expect(page.get_by_text('Current location added.',exact=False)).to_be_visible()
    page.get_by_role('button',name='Save discovery',exact=True).click()
    expect(page.get_by_role('heading',name='QA bluebell woodland')).to_be_visible()
    page.reload(wait_until='domcontentloaded')
    expect(page.get_by_role('heading',name='QA bluebell woodland')).to_be_visible(timeout=15000)
    print('PASS: offline capture, GPS, IndexedDB save and offline reload')
    ctx.set_offline(False)
    page.get_by_role('button',name='Create account',exact=True).click()
    email=f'qa-browser-{uuid.uuid4().hex[:10]}@example.test'
    page.get_by_label('Your name',exact=True).fill('QA Explorer')
    page.get_by_label('Email',exact=True).fill(email)
    page.get_by_label('Password',exact=True).fill('Fieldnotes-QA-2026-Only!')
    page.get_by_role('button',name='Create my account',exact=True).click()
    page.wait_for_function("fetch('/api/observations').then(r=>r.json()).then(x=>x.observations?.length === 1)",timeout=20000)
    print('PASS: real registration, guest adoption, upload and server persistence')
    page.get_by_role('button',name='Map',exact=True).click()
    expect(page.locator('.leaflet-interactive')).to_have_count(1)
    page.get_by_role('button',name='QA bluebell woodland, Flowers',exact=True).click()
    expect(page.get_by_role('heading',name='From your field journal')).to_be_visible()
    expect(page.get_by_text('51.75200, -1.25800',exact=False)).to_be_visible()
    page.get_by_role('button',name='Add a note or correct the name').click()
    page.get_by_label('Scientific name, if known').fill('Hyacinthoides non-scripta')
    page.get_by_role('button',name='Save changes',exact=True).click()
    with page.expect_download() as download_info:
        page.get_by_role('button',name='Photo & story',exact=True).click()
    downloaded=download_info.value
    assert downloaded.suggested_filename.endswith('.png')
    page.get_by_role('button',name='Close',exact=True).click()
    page.get_by_role('button',name='Collection',exact=True).click()
    expect(page.get_by_text('Hyacinthoides non-scripta',exact=True)).to_be_visible()
    page.get_by_role('button',name='Milestones',exact=True).click()
    expect(page.get_by_role('heading',name='First wonder',exact=True)).to_be_visible()
    print('PASS: colour-coded map, marker detail, corrections, species stats, milestones and story sharing')
    page.get_by_role('button',name='Journal',exact=True).click()
    page.get_by_role('button',name='Dates',exact=True).click()
    page.get_by_label('From',exact=True).fill('2099-01-01')
    expect(page.get_by_role('heading',name='No discoveries in this little corner yet')).to_be_visible()
    page.get_by_role('button',name='Clear filters',exact=True).click()
    page.get_by_role('textbox',name='Search discoveries',exact=True).fill('not present')
    expect(page.get_by_role('heading',name='No discoveries in this little corner yet')).to_be_visible()
    page.get_by_role('button',name='Clear filters',exact=True).click()
    print('PASS: search and date filters')
    ctx.set_offline(True)
    page.locator('input[type=file]').nth(1).set_input_files('public/woodland.jpg')
    page.get_by_label('A name, if you know it').fill('QA queued discovery')
    page.get_by_role('button',name='Save discovery',exact=True).click()
    expect(page.get_by_role('heading',name='QA queued discovery')).to_be_visible()
    page.reload(wait_until='domcontentloaded')
    expect(page.get_by_role('heading',name='QA queued discovery')).to_be_visible(timeout=15000)
    ctx.set_offline(False)
    page.wait_for_function("fetch('/api/observations').then(r=>r.json()).then(x=>x.observations?.length === 2)",timeout=20000)
    print('PASS: signed-in offline queue survives restart and automatically uploads on reconnect')
    assert not page.evaluate('document.documentElement.scrollWidth > innerWidth')
    assert not errors,errors
    print('PASS: mobile layout and no uncaught browser errors')
    ctx.close();browser.close()
