/** Pure desktop achievement rules mirror nativeapp/Achievements.java; stable IDs preserve history. */
export type AchievementPhoto = {category?:string;scientificName?:string;confirmed?:boolean;identification?:{confidence?:string}|null;latitude?:number|null;longitude?:number|null;place?:string;name?:string;localDate?:string;localHour?:number;capturedAt?:string;timezone?:string;archived?:boolean};
export type Achievement = {id:string;name:string;description:string;layer:number;goal:number;progress:number};
export type AchievementLedger = Record<string,string>;
export const achievementLevels = [
  {name:"Soil",colour:"#76543e",background:"#f0e6de",ink:"#76543e",onColour:"#ffffff",threshold:0,description:"Every trail begins with the soil beneath your feet."},
  {name:"Clay",colour:"#a94f3a",background:"#ffe9df",ink:"#a94f3a",onColour:"#ffffff",threshold:12,description:"Earth shaped by water: look for colour, texture and tiny details."},
  {name:"Flint",colour:"#4f6576",background:"#e6edf2",ink:"#4f6576",onColour:"#ffffff",threshold:30,description:"A quiet stone with a sharp story, revealed by closer looking."},
  {name:"Quartz",colour:"#76559a",background:"#eee5f7",ink:"#76559a",onColour:"#ffffff",threshold:60,description:"A glint in the rock: more kinds of discoveries, in different light."},
  {name:"Amber",colour:"#965408",background:"#ffedcf",ink:"#965408",onColour:"#ffffff",threshold:100,description:"A rare fragment of ancient sunlight, keeping a moment forever."},
  {name:"Gold",colour:"#cfa830",background:"#fff2c7",ink:"#76601a",onColour:"#3d330b",threshold:150,description:"The rarest trail treasure: a rich collection of lasting memories."},
] as const;
const categories=["plants","flowers","bugs","birds","animals","fungi","landmarks","other"];
const holidays=[["01-01", "A fresh beginning", "New Year’s Day"], ["01-25", "Burns Night wander", "25 January"], ["02-02", "Winter turning", "2 February"], ["02-14", "Love your outdoors", "Valentine’s Day"], ["02-29", "One in four", "Leap Day, 29 February"], ["03-01", "Daffodil day", "St David’s Day"], ["03-17", "A little green", "St Patrick’s Day"], ["03-20", "Spring’s doorstep", "20 March"], ["04-01", "No fooling nature", "1 April"], ["04-22", "Our remarkable Earth", "Earth Day, 22 April"], ["04-23", "English countryside", "St George’s Day"], ["05-01", "May Day moment", "1 May"], ["05-20", "Busy little pollinators", "World Bee Day, 20 May"], ["05-22", "Life in all its forms", "Biodiversity Day, 22 May"], ["06-05", "A greener thought", "Environment Day, 5 June"], ["06-08", "Blue planet", "World Oceans Day, 8 June"], ["06-21", "Long light", "21 June"], ["07-01", "High summer", "1 July"], ["08-01", "August abundance", "1 August"], ["09-22", "Autumn’s doorstep", "22 September"], ["10-04", "Animal appreciation", "World Animal Day, 4 October"], ["10-31", "Spooky little wonders", "Halloween"], ["11-05", "November glow", "5 November"], ["11-11", "A quiet remembrance", "11 November"], ["11-30", "St Andrew’s discovery", "St Andrew’s Day"], ["12-21", "Winter light", "21 December"], ["12-24", "A Christmas Eve pause", "Christmas Eve"], ["12-25", "Christmas Day wonder", "Christmas Day"], ["12-26", "Boxing Day fresh air", "Boxing Day"], ["12-31", "The year’s last page", "New Year’s Eve"], ["easter", "An Easter discovery", "Easter Sunday"]] as const;
const subjects=[["oak", "Oak acquaintance"], ["beech", "Beech beauty"], ["pine", "Pine scent"], ["birch", "Silver storyteller"], ["willow", "Willow whisper"], ["ash", "Ash encounter"], ["holly", "Winter evergreen"], ["hazel", "Hazel haven"], ["sycamore", "Winged seeds"], ["yew", "Old woodland guardian"], ["rowan", "Rowan visitor"], ["chestnut", "Chestnut curiosity"], ["maple", "Maple moment"], ["alder", "Waterside alder"], ["daisy", "Daisy delight"], ["dandelion", "Everyday sunshine"], ["bluebell", "A bluebell moment"], ["buttercup", "Golden little cup"], ["foxglove", "Foxglove bells"], ["poppy", "A poppy pause"], ["snowdrop", "Winter’s white promise"], ["daffodil", "Spring trumpet"], ["primrose", "Primrose promise"], ["clover", "Clover close-up"], ["lavender", "Lavender lull"], ["heather", "Heather hillside"], ["orchid", "An orchid encounter"], ["rose", "Rose discovery"], ["nettle", "Look again at nettles"], ["fern", "Fern unfurling"], ["moss", "A tiny green forest"], ["ivy", "Ivy invitation"], ["robin", "Robin company"], ["blackbird", "Blackbird hello"], ["sparrow", "Sparrow spotter"], ["blue tit", "Blue tit glimpse"], ["great tit", "Great tit moment"], ["wren", "Little wren"], ["woodpecker", "Woodland drummer"], ["kingfisher", "A flash of blue"], ["heron", "Patient waterside watcher"], ["owl", "Owl encounter"], ["duck", "Duckside diary"], ["swan", "Swan serenity"], ["buzzard", "Buzzard above"], ["pigeon", "Pigeon perspective"], ["butterfly", "Butterfly pause"], ["bee", "Bee busy"], ["ladybird", "Spotted little visitor"], ["dragonfly", "Dragonfly shimmer"], ["beetle", "Beetle beginnings"], ["moth", "Moth moment"], ["spider", "Silken world"], ["snail", "Slow and lovely"], ["ant", "Ant’s eye view"], ["grasshopper", "Meadow musician"], ["fox", "Fox encounter"], ["squirrel", "Squirrel surprise"], ["deer", "Deer diary"], ["rabbit", "Rabbit ramble"], ["hedgehog", "Prickly little neighbour"], ["badger", "Badger moment"], ["hare", "Hare encounter"], ["otter", "Otter occasion"], ["mushroom", "Mushroom mystery"], ["lichen", "Lichen, looked at"], ["bridge", "Bridge story"], ["river", "River reflection"], ["waterfall", "Waterfall wonder"], ["castle", "Castle curiosity"]] as const;
export function achievementLevel(earned:number) {let level=0;for(let i=1;i<achievementLevels.length;i++)if(earned>=achievementLevels[i].threshold)level=i;return level;}
function count(map:Map<string,number>,key:string) {map.set(key,(map.get(key)||0)+1);}
function captureDay(record:AchievementPhoto) {
  if(record.localDate)return record.localDate;
  try{const parts=new Intl.DateTimeFormat('en-GB',{timeZone:record.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(record.capturedAt||''));return ['year','month','day'].map(type=>parts.find(p=>p.type===type)?.value).join('-');}catch{return '';}
}
function validDay(day:string) {if(!/^\d{4}-\d{2}-\d{2}$/.test(day))return null;const date=new Date(day+'T00:00:00Z');return Number.isFinite(date.getTime())&&date.toISOString().slice(0,10)===day?date:null;}
export function easterDay(year:number) {
  const a=year%19,b=Math.floor(year/100),c=year%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),n=h+l-7*m+114;
  return `${String(year).padStart(4,'0')}-${String(Math.floor(n/31)).padStart(2,'0')}-${String(n%31+1).padStart(2,'0')}`;
}
export function evaluateAchievements(records:readonly AchievementPhoto[]):Achievement[] {
  const out:Achievement[]=[],species=new Set<string>(),areas=new Set<string>(),days=new Set<string>(),months=new Set<string>(),hours=new Set<number>(),week=new Set<number>(),monthNumbers=new Set<number>(),counts=new Map<string,number>(),names=new Map<string,number>(),dates=new Map<string,number>(),categorySpecies=new Map<string,Set<string>>();
  let gps=0,named=0,early=0,dawn=0,evening=0,night=0,weekends=0,weekdays=0;
  const add=(id:string,name:string,description:string,layer:number,goal:number,progress:number)=>out.push({id,name,description,layer,goal,progress:Math.min(goal,Math.max(0,progress))});
  for(const record of records) {
    const category=record.category||'other';count(counts,category);
    const scientificName=(record.scientificName||'').trim();
    if(scientificName.split(/\s+/).length>=2&&!/\b(spp?|species)\.?$/i.test(scientificName)&&(record.confirmed||!record.identification||record.identification.confidence!=='low')) {
      const key=(record.scientificName||'').toLowerCase();species.add(key);if(!categorySpecies.has(category))categorySpecies.set(category,new Set());categorySpecies.get(category)!.add(key);
    }
    if(typeof record.latitude==='number'&&typeof record.longitude==='number'&&Number.isFinite(record.latitude)&&Number.isFinite(record.longitude)&&Math.abs(record.latitude)<=90&&Math.abs(record.longitude)<=180){gps++;areas.add(`${record.latitude.toFixed(2)},${record.longitude.toFixed(2)}`);}
    if(record.place?.trim())named++;
    count(names,((record.name||'A little mystery')+' '+(record.scientificName||'')).toLowerCase());
    const day=captureDay(record),date=validDay(day);if(!date)continue;
    const month=date.getUTCMonth()+1,weekday=date.getUTCDay()||7;
    days.add(day);months.add(day.slice(0,7));week.add(weekday);monthNumbers.add(month);count(dates,'month-'+month);count(dates,'weekday-'+weekday);count(dates,day.slice(5));if(day===easterDay(date.getUTCFullYear()))count(dates,'easter');
    if(weekday>=6)weekends++;else weekdays++;
    const hour=record.localHour??-1;if(Number.isInteger(hour)&&hour>=0&&hour<24){hours.add(hour);if(hour<9)early++;if(hour>=5&&hour<8)dawn++;if(hour>=17&&hour<21)evening++;if(hour>=21||hour<5)night++;count(dates,'hour-'+hour);}
  }
  const goals=[1,5,10,25,50,100,200,350,500,750,1000];goals.forEach((goal,index)=>add('photos-'+goal,index===0?'First wonder':'A scrapbook of '+goal,'Save '+goal+' discoveries.',Math.min(5,Math.floor(index/2)),goal,records.length));
  [3,5,10,20,35,50,75,100].forEach((goal,index)=>add('species-'+goal,'Meet '+goal+' species','Collect '+goal+' different identified species.',Math.min(5,index),goal,species.size));
  for(const category of categories)for(let i=0;i<6;i++) {
    const goal=[1,5,15,30,60,100][i];add(category+'-'+goal,category[0].toUpperCase()+category.slice(1)+' · '+goal,'Photograph '+goal+' discoveries in '+category+'.',i,goal,counts.get(category)||0);
    if(category!=='other'&&category!=='landmarks'){const goal=[1,3,5,10,20,30][i];add(category+'-species-'+goal,'Different '+category+' · '+goal,'Meet '+goal+' distinct identified species of '+category+'.',i,goal,categorySpecies.get(category)?.size||0);}
  }
  for(let i=0;i<6;i++) {const goal=[1,3,7,15,30,60][i];add('areas-'+goal,'New corners · '+goal,'Make discoveries in '+goal+' different map areas (about 1 km across).',i,goal,areas.size);add('days-'+goal,'Days worth keeping · '+goal,'Photograph something on '+goal+' different days. They need not be consecutive.',i,goal,days.size);const monthGoal=[1,2,4,6,12,24][i];add('months-'+monthGoal,'A journal through time · '+monthGoal,'Make discoveries in '+monthGoal+' different calendar months.',i,monthGoal,months.size);}
  add('all-kinds','A little of everything','Notice all eight categories of discoveries.',2,8,counts.size);add('all-week','Every day has a story','Photograph something on each day of the week.',2,7,week.size);add('all-months','A whole year of wonder','Make a discovery in every month of the year.',4,12,monthNumbers.size);add('hours-8','Different light','Collect discoveries in eight different hours of the day.',3,8,hours.size);add('hours-16','Round the clock','Collect discoveries in sixteen different hours. No need to stay up late.',5,16,hours.size);
  const timeNames=['Early bird','First light','Evening glow','After dark','Weekend wonders','An ordinary day, noticed','On the map','A sense of place'],timeDesc=['before 9 am','between 5 and 8 am','between 5 and 9 pm','between 9 pm and 5 am','at the weekend','on weekdays','with saved coordinates','with a place name'],values=[early,dawn,evening,night,weekends,weekdays,gps,named];
  for(let t=0;t<values.length;t++)for(let i=0;i<3;i++){const goal=[1,5,20][i];add('time-'+t+'-'+goal,timeNames[t]+(i===0?'':' · '+goal),'Save '+goal+' discoveries '+timeDesc[t]+'.',Math.min(5,i+t%2),goal,values[t]);}
  const monthNames=['January','February','March','April','May','June','July','August','September','October','November','December'];
  for(let month=1;month<=12;month++)for(let i=0;i<2;i++){const label=monthNames[month-1],goal=i===0?1:10;add('month-'+month+'-'+goal,label+' memories'+(i===0?'':' · 10'),'Save '+goal+' discoveries photographed in '+label+'.',i===0?1:3,goal,dates.get('month-'+month)||0);}
  ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].forEach((label,index)=>add('weekday-'+(index+1),label+' pause','Save five discoveries photographed on a '+label+'.',2,5,dates.get('weekday-'+(index+1))||0));
  for(const [id,name,label] of holidays)add('calendar-'+id,name,'Photograph a discovery on '+label+'. Earn it once and keep it forever.',1,1,dates.get(id)||0);
  subjects.forEach(([key,label],index)=>{let n=0;const pattern=new RegExp('\\b'+key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\b');for(const [identity,count] of names)if(pattern.test(identity))n+=count;add('subject-'+key,label,'Photograph a discovery identified as '+key+'.',2+index%4,1,n);add('subject-'+key+'-5','Getting to know '+key,'Photograph '+key+' on five occasions.',4+index%2,5,n);});
  return out;
}
export function earnAchievements(prior:AchievementLedger,badges:readonly Achievement[],earnedAt:string):AchievementLedger {const merged={...prior};for(const badge of badges)if(badge.progress>=badge.goal&&!merged[badge.id])merged[badge.id]=earnedAt;return merged;}
export function mergeAchievementLedgers(...ledgers:AchievementLedger[]):AchievementLedger {const out:AchievementLedger={};for(const ledger of ledgers)for(const [id,when] of Object.entries(ledger))if(Number.isFinite(Date.parse(when))&&(!out[id]||when<out[id]))out[id]=when;return out;}
export function validAchievementLedger(value:unknown):AchievementLedger {if(!value||typeof value!=='object'||Array.isArray(value))return{};const ids=new Set(evaluateAchievements([]).map(badge=>badge.id));return Object.fromEntries(Object.entries(value).filter(([id,when])=>ids.has(id)&&typeof when==='string'&&Number.isFinite(Date.parse(when)))) as AchievementLedger;}
