'use client';
import {useState,useEffect} from 'react';
import AuthProvider,{useAuth} from '../components/AuthProvider';
function Invitation(){
 const {user,loading,signIn,signUp}=useAuth();const [token,setToken]=useState(''),[register,setRegister]=useState(false),[message,setMessage]=useState(''),[photo,setPhoto]=useState<any>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{setToken(new URLSearchParams(location.search).get('token')||'');},[]);
 async function accept(){setBusy(true);try{const r=await fetch('/api/social/invite',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});const data=await r.json() as any;if(!r.ok)throw Error(data.error);const p=await fetch('/api/social/photos/'+data.id);const result=await p.json() as any;if(!p.ok)throw Error(result.error);setPhoto(result.photo);setMessage('Invitation accepted. This photo is also in Invited on the app map.');history.replaceState(null,'','/invite');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <main className="legal-page"><a href="/">← My Trail Log</a><h1 style={{fontFamily:'Kalam, cursive'}}>A discovery for you</h1><p>This invitation shares a photo privately. Sign in with the email address the invitation was sent to.</p>{loading?<p>Opening your journal…</p>:!user?<form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const error=register?await signUp(String(f.get('email')),String(f.get('password')),String(f.get('name'))):await signIn(String(f.get('email')),String(f.get('password')));setMessage(error||'Signed in. You can now open the invitation.');setBusy(false);}}>{register&&<label>Your account name<input name="name" required autoComplete="name"/></label>}<label>Email<input name="email" type="email" required autoComplete="email"/></label><label>Password<input name="password" type="password" required minLength={8} autoComplete={register?'new-password':'current-password'}/></label><button className="button primary" disabled={busy}>{register?'Create account':'Sign in'}</button><button type="button" className="button secondary" onClick={()=>setRegister(!register)}>{register?'I have an account':'Create an account'}</button></form>:!photo?<button className="button primary" onClick={accept} disabled={busy||!token}>{busy?'Opening…':'Accept invitation'}</button>:<article><img src={photo.photoUrl} alt={photo.name} style={{width:'100%',borderRadius:24}}/><h2>{photo.name}</h2><p>By @{photo.author.username} · {photo.place} · {photo.localDate}</p><p>{photo.summary}</p><p>{photo.interestingInfo}</p></article>}<p role="status">{message}</p><p><a href="/community-rules">Sharing guidelines</a> · <a href="/privacy">Privacy</a></p></main>;
}
export default function Invite(){return <AuthProvider><Invitation/></AuthProvider>}
