import PolicyLayout from "../components/PolicyLayout";
export const metadata = { title: "Cookies & device storage · My Trail Log" };
export default function CookiesPage() { return <PolicyLayout title="Cookies & device storage" intro="Storage helps you sign in, keep a journal offline and remember your choices. There are no advertising trackers.">
  <h2>Sign-in cookie</h2><p>The website uses the first-party <code>fieldnotes_session</code> cookie to maintain sign-in. It is HttpOnly and protected in secure production connections. This is necessary for account access and is removed on successful sign-out; otherwise it expires after 30 days. It is not an advertising or cross-site tracking cookie.</p>
  <h2>Offline journal and preferences</h2><p>The website uses IndexedDB for local photos, journal data, pending changes, a last signed-in account record and preferences. A service worker caches public resources and the journal shell to support offline opening. Account APIs and administrator pages are not cached as offline pages. Local journal photos are account-scoped.</p><p>Local storage survives until you clear it, delete account data on that browser or the browser removes it. Clearing it may permanently remove unsynced photos; export or sync first. Signing out does not delete the local journal. Protect a shared device: someone with access to its unlocked storage may be able to access local files.</p>
  <h2>Android device storage</h2><p>The native app uses private files and a database for photos, journal data and achievements, plus Android Keystore to protect the sign-in session. Preferences retain choices such as weather effects and alerts. Camera, location, contacts and notification permissions are controlled in Android Settings.</p>
  <h2>No optional tracking tools</h2><p>We do not use advertising, behavioural analytics or marketing cookies. Necessary account and offline features do not require an optional advertising consent banner. If optional tracking is added, we will update this page and consent choices first. Our host may process essential network and security information under its own policy.</p>
  <h2>Manage or remove storage</h2><p>Use your browser’s site-data settings to view or clear storage. On Android, clear app storage or uninstall to remove local data. Remove exports separately. To remove online data, use <a href="/delete-account">account deletion</a>; clearing cookies or uninstalling is not online deletion. Read the <a href="/privacy">privacy policy</a> or email <a href="mailto:ntracey@gmail.com">ntracey@gmail.com</a> for help.</p>
  </PolicyLayout>; }
