import { Mail } from "lucide-react";
import WebsiteShell from "../components/WebsiteShell";
export const metadata = { title: "Support & help · My Trail Log" };
export default function SupportPage() { return <WebsiteShell><section className="company-container company-support"><div className="company-support-head"><div><p className="company-kicker">A little help along the way</p><h1>Let’s get you<br/><em>back to exploring.</em></h1></div><p>For journal questions, publication concerns or subscription problems, send a note. My Trail Log is currently operated by Nathan Tracey.</p></div><div className="company-support-contact"><div><h3>Talk to Nathan</h3><p>Support, privacy requests and content reviews.</p></div><a className="company-button company-button-primary" href="mailto:ntracey@gmail.com"><Mail size={18}/>ntracey@gmail.com</a></div><div className="company-faq">
  <details><summary>How do I open my journal on a computer?</summary><p><a href="/journal">Open the desktop journal</a> and sign in with the same email and password as the Android app. Cloud photos appear when connected. Local-only photos on another device need to sync first.</p></details>
  <details><summary>Can I take photos with no signal?</summary><p>Yes. Android saves photos and capture information locally, then can sync when connected. Identification and avatar generation need the online service. Photos above your upload allowance stay pending and are not removed from your phone.</p></details>
  <details><summary>Where is each photo’s location?</summary><p>Grant foreground location once and Android can reuse it for captures. A brief GPS fix supplies coordinates; a place lookup adds a name. Permission, signal and accuracy affect the result. There is no background tracking. Check a location before sharing.</p></details>
  <details><summary>How do I get a copy of everything?</summary><p>Use the account’s free photo and data ZIP download. It includes your photos and available journal data. Keep it private: saved coordinates and notes can be sensitive. Exports remain free without a subscription.</p></details>
  <details><summary>How do I cancel a subscription or trial?</summary><p>Manage Android subscriptions in <a href="https://play.google.com/store/account/subscriptions" rel="noopener noreferrer">Google Play</a> before renewal or the trial deadline. Deleting an account or uninstalling does not cancel billing. Until Google Play setup is complete, paid checkout is unavailable.</p></details>
  <details><summary>What do Archive and Unpublish do?</summary><p>Archive removes a photo from the active journal and publication while keeping its private data. Restore it in settings. Unpublish revokes shared access and retains the private entry. Unpublish all requires confirmation and cancels pending bulk publication.</p></details>
  <details><summary>How do I report a photo or appeal a decision?</summary><p>Use Report on a shared photo or email its identifier to support. Reports can hide a photo during review. You can block users. Contact support to review a restriction; automatic checks are imperfect. Avoid sending unnecessary private information.</p></details>
  <details><summary>How do Smart AI and closer reviews work?</summary><p>Smart AI suggests an identity for each online photo. Uncertain photos may automatically receive a more detailed review while your plan’s closer-review allowance is available. Tentative entries also offer “Try a closer look” for an explicit retry. This is a separate allowance from cloud photos; reserved or failed review attempts still count. After it is used, initial suggestions continue and may be marked tentative. Membership shows your remaining allowances. Annual extra reviews apply only to annual bonus photos.</p></details>
  <details><summary>Is an identification always correct?</summary><p>No. A tentative label means the suggestion remains uncertain; a closer review does not guarantee a correct answer. Use the references and correct a suggestion if necessary. Do not rely on the app for edibility, medicine or wildlife handling. Historical uses describe history, not treatment instructions.</p></details>
  <details><summary>How do I delete my account?</summary><p>Export what you want first. Use account settings or <a href="/delete-account">the deletion page</a> to remove your live online account. Exports and copies on other devices need separate removal. Cancel any Google Play subscription separately.</p></details>
  </div><p className="company-pricing-footnote">Postal contact: Nathan Tracey, 422 Milton Road, Waterlooville, PO8 8LD, United Kingdom.</p><div id="credits" className="company-credits"><h2>Photo & data credits</h2><p>Bundled woodland photography: Rob Wingate / Unsplash. Robin: Richard Bell / Unsplash. Red fox: Charles Jackson / Unsplash. Photos use the Unsplash License; source links are in the app’s field guide. Screenshots show illustrative demonstration discoveries.</p><p>Maps and places: OpenStreetMap contributors, Photon and Postcodes.io. Weather: Open-Meteo and MET Norway (CC BY 4.0). References: Wikipedia and GBIF. Fonts: DM Sans and Kalam, SIL Open Font License.</p><p>Include your app version, Android version and a short description when emailing support. Never send a password, API key, signing key or payment card details.</p></div></section></WebsiteShell>; }
