import WebsiteShell from "../components/WebsiteShell";
import Plans from "../components/Plans";
export const metadata = { title: "Plans & subscriptions · My Trail Log", description: "Compare My Trail Log’s free journal and Google Play subscriptions, with Smart AI suggestions and automatic closer reviews. Downloads always remain free." };
export default function PricingPage() { return <WebsiteShell><section className="company-container company-pricing-page"><div className="company-section-heading"><p className="company-kicker">Choose room for your discoveries</p><h1>Your journal.<br/><em>Your own pace.</em></h1><p>Every plan keeps your photos private by default, includes the map and scrapbook, and lets you download your photos and data for free.</p></div><Plans/><div className="company-pricing-details">
  <article><h3>What counts as a photo?</h3><p>A new photo first saved to your online journal counts towards the month’s photo allowance. Editing, restoring an archive, downloading, sharing or viewing an existing photo does not use another slot. Capture on your phone remains available offline; an upload can wait until you have room.</p></article>
  <article><h3>What is a closer review?</h3><p>Smart AI gives each online photo an identification suggestion. When a photo is uncertain, the service may automatically use a more detailed review from your separate closer-review allowance. If an entry stays tentative, you can also choose “Try a closer look” when review capacity is available. A closer review does not guarantee a species identification. Once the allowance is exhausted, the initial suggestion can remain tentative. Reserved or failed review attempts count; deleting an entry does not return an attempt.</p></article>
  <article><h3>When do allowances reset?</h3><p>Normal photo and closer-review allowances reset on the first day of each UTC calendar month. Unused monthly allowance does not roll over. Existing uploaded photos are not counted again. A paid yearly plan caps normal usage at twelve monthly allowances per membership year: 3,600 photos and 720 closer reviews. It also includes 150 bonus photos and up to 30 extra closer reviews for those bonus photos. Crossing calendar-month boundaries cannot increase the annual total. Unused annual extras expire at the paid year’s end.</p></article>
  <article><h3>A month to try it</h3><p>Eligible customers can receive a one-month free trial when an eligible Google Play offer is available. The app and Play checkout show the plan, trial end, first payment and renewal price before purchase. The trial allows the selected paid plan’s monthly photo allowance and closer-review allowance in total during its trial month, across calendar resets. Annual extras are not included in a trial. Unless cancelled in time, a trial turns into a paid subscription. The free plan itself has no subscription or payment requirement.</p></article>
  <article><h3>Renewal and cancellation</h3><p>Subscriptions renew automatically through Google Play unless you cancel. You can manage or cancel from the app’s subscription page or <a href="https://play.google.com/store/account/subscriptions" rel="noopener noreferrer">Google Play subscriptions</a>. Cancellation normally ends renewal while access continues to the paid period’s end. Google Play shows the exact terms and trial deadline for your purchase.</p></article>
  <article><h3>If you reach your allowance</h3><p>Your current photos, archive and data stay available. Downloading them remains free. New online uploads wait until the next reset or a verified plan change gives you space. Reaching the closer-review limit does not use up your remaining photo allowance: initial AI suggestions continue, with uncertainty shown. Deleting a photo does not undo a used photo slot or review attempt.</p></article>
  <article><h3>Prices and refunds</h3><p>The prices above are our UK plan prices. Your actual currency, applicable tax, eligible offers and total are shown by Google Play before you pay. Paid checkout is unavailable until Google Play configuration is complete. No payment card details are stored by My Trail Log. For a purchase problem or refund request, use <a href="https://support.google.com/googleplay/answer/2479637" rel="noopener noreferrer">Google Play’s refund process</a> or <a href="/support">contact us</a>. Your statutory consumer rights remain in place.</p></article>
  </div><p className="company-pricing-footnote">Please read our <a href="/terms">terms</a> and <a href="/privacy">privacy policy</a>. Paid access is granted only after a Google Play purchase is verified.</p></section></WebsiteShell>; }
